flatironinstitute/finufft

python_tests/accuracy_speed_tests.py
The python tests are not refactored after name changes of the python module. Please merge
=> [pytest] fix calls to .nufftXd

matlab/finufft_opts.m
=> Make empty options fields do default values

src/finufft.cpp, src/utils.cpp, test/dumbinputs.cpp, test/finufft1d_test.cpp, test/finufft1dmany_test.cpp, test/finufft2d_test.cpp, test/finufft2dmany_test.cpp, test/finufft3d_test.cpp, test/finufft3dmany_test.cpp, test/finufftGuru_test.cpp, test/manysmallprobs.cpp, test/results/check1d.sh.refout, test/results/check2d.sh.refout, test/results/check3d.sh.refout, test/results/dumbinputs.refout, test/results/nuffttestnd_results_v1.2_i7_gcc92.txt, test/results/spreadtestnd_results_v1.2_i7_gcc92.txt
This tidied up 6 tests (dim 1,2,3 and simple vs many), finufftGuru_test, and dumbinputs (adding a couple of guru immediate destroy cases that took a while to debug).
This is all about improving reliability, although there's much more input-cleaning and dumbinput testing    to do for the guru interface.
Now "make test" works.
=> Alexguru improved tests and "make test" working

makefile, test/dumbinputs.cpp, test/finufft1d_test.cpp, test/finufft1dmany_test.cpp, test/finufft2d_test.cpp, test/finufft2dmany_test.cpp, test/finufft3d_test.cpp, test/finufft3dmany_test.cpp, test/finufftGuru_test.cpp
The tests were broken by the dual-precision stuff, but this should make them run again.
=> Fix tests in guru

docs/python.rst
Address some issues pointed out by @ahbarnett.
=> Gi v2 pydoc fix

python/finufftpy/_interfaces.py
It's not the prettiest, but it does the trick and should be fairly easy to maintain.
Fixes #120.
=> Add templated docstrings for Python

docs/python.rst, python/finufft/__init__.py, python/finufft/_interfaces.py
=> Update docstrings for Plan interface

python/requirements.txt, python/setup.py
Reverts flatironinstitute/finufft#147
=> Revert "Cleanup setup.py"

python/finufft/_finufft.py, python/finufft/_interfaces.py
Mostly cleanup, simplification.
=> Address some outstanding issues from #137

docs/install.rst, make.inc.windows_mingw, makefile
Finally, I took the time to sit down and document my experiences with finufft on Windows. Please have a look at the added documentation section and the changes to the Makefile. Since this pull request is in draft mode, you should be able to modify my proposal as needed.
Best,
Jonas
=> Installation instructions for windows

docs/devnotes.rst, python/finufft/__init__.py
=> Add py __version__

python/finufft/_interfaces.py
Instead, we call _ensury_array_type, which provides more informative
error messages and does a more thorough check on the array type (dtype,
memory layout, writeability). Modeled after @dstein's suggesting in #232.
Also removes the the `is_single` plan attribute in favor of `dtype`,
which holds the complex dtype.
Fixes #232.
=> Replace old `_*chk*` functions

docs/cex.rst, docs/install.rst
Dear all,
I have added some documentation on how to easily use finufft in cmake projects and how to achieve thread safety.
Cheers,
Marco
=> Documentation about CPM and thread safety 

python/finufft/_interfaces.py
Closes #266 
https://docs.python.org/3/library/warnings.html#available-context-managers
=> Use context manager for manipulating `warnings`

examples/cuda/getting_started.py
Forgot to add this one when setting up the CUDA docs.
=> Add missing py getting started example

cufinufft/.bumpversion.cfg, cufinufft/CHANGELOG, cufinufft/README.md, cufinufft/ci/build-wheels.sh, cufinufft/ci/distribution_helper.sh, cupython/cufinufft/README.md, cupython/cufinufft/__init__.py, cupython/cufinufft/docs/conf.py, cupython/cufinufft/requirements.txt, cupython/setup.py
Brings cufinufft code up to date with 1.3 (see cufinufft repository).
=> Cufinufft v1.3

python/cufinufft/tests/test_examples.py
CI broke after #282. This fixes it.
=> cuda: fix test_examples.py

src/finufft.cpp
try to address issue #269 , not sure this is the proper way. Maybe there is better ways.
=> attemp to fix memory leak for repeatedly calling setpts

python/cufinufft/tests/test_array_ordering.py, python/cufinufft/tests/test_basic.py, python/cufinufft/tests/test_error_checks.py, python/cufinufft/tests/test_multi.py, python/cufinufft/tests/test_simple.py, python/cufinufft/tests/utils.py
Tests the plan and simple interfaces for various configurations of shapes, number of points, tolerances, and dtypes.
=> Update and extend cufinufft unit tests

include/cufinufft/impl.h
=> cuda: sanity check inputs

src/finufft.cpp
This is a tentative fix for #346. 
See: http://www.fftw.org/doc/Thread-safety.html
> The upshot is that the only thread-safe routine in FFTW is fftw_execute (and the new-array variants thereof). All other routines (e.g. the planner) should only be called from one thread at a time.
This means that fftw malloc/free/etc calls are also not thread safe.
=> bugfix: put all non-execute fftw calls in critical regions #346

Jenkinsfile
Attempts at fixing recent numba CI failures
=> ci: pin numba to 0.57.1 for now (0.58.0 failing)

python/finufft/finufft/_interfaces.py
Try to fix swallowing singleton dimensions issue #359 caught by Michael and dtype warning issue in PR #338 caught by Brian.
=> fix dim squeeze issue #359 and dtype waring in PR#338

CHANGELOG, python/finufft/finufft/_interfaces.py, python/finufft/test/test_finufft_plan.py
fix issue #367 to support batch dimension of length 1 input for python interface.
=> python interface supports batch dimension of length 1, fix issue #367

python/cufinufft/cufinufft/_simple.py
Basically same as for finufft (CPU).
Fixes #312.
=> Document cufinufft simple API

include/cufinufft.h
=> Include stdint.h in cufinufft.h

python/finufft/finufft/_interfaces.py
Just some maintenance to the docstrings. Most important is update example paths.
Built docs are here: https://users.flatironinstitute.org/~janden/finufft-docs/
=> Update finufft docstrings

docs/c_gpu.rst, docs/cufinufft_migration.rst, docs/index.rst, docs/python_gpu.rst, python/TODO, python/cufinufft/README.md
Outlining the API changes between v1.3 and v2.2.
=> Add cuFinufft migration guide

python/finufft/test/test_finufft_plan.py
Integrate it into the matrix of tests for type 1 and add it for the type 2 tests as well.
=> Improve testing of modeord option

docs/install_gpu.rst
=> docs: fix CUDA version typo in GPU install docs

src/spreadinterp.cpp, test/CMakeLists.txt, test/README, test/finufft3dkernel_test.cpp
I have drafted a test for kerevalmeth. I am not testing against ground truth as the finufftNd_tests are already doing so but that can be added.
=> kerevalmeth test 

CMakeLists.txt, include/finufft/defs.h, include/finufft/spreadinterp.h, makefile, src/spreadinterp.cpp
The interp code is vectorized similarly to the spreader. Results are in https://github.com/flatironinstitute/finufft/discussions/452
=> Interp vectorization

docs/python.rst
Partially fixes #479 and #506.
=> Add instructions for building py from source

python/cufinufft/pyproject.toml, python/finufft/pyproject.toml
Reverts flatironinstitute/finufft#538
=> Revert "Do not compile Python wheels with -march=native"

python/cufinufft/cufinufft/_plan.py, python/cufinufft/tests/test_error_checks.py, python/finufft/finufft/_interfaces.py, python/finufft/test/test_finufft_plan.py
=> Remove conversion for real dtypes

.pre-commit-config.yaml
changed cmake-formatter with a better hook. Updated version of other hooks
https://github.com/flatironinstitute/finufft/pull/619#issuecomment-2625670587
=> updating hooks

CHANGELOG, src/cuda/1d/spreadinterp1d.cuh, test/cuda/CMakeLists.txt
=> cufinufft 1d spreader sm method check

.github/workflows/cmake_ci.yml, .github/workflows/valgrind.yml, test/finufft1d_test.cpp
Given the most recent issue, I am adding a workflow that runs valgrind (only once) It does not take much time. 
This is to prevent memory leaks and (hopefully) undefined behaviors in the future. 
example fail ( I artifically  added a leak):
https://github.com/DiamonDinoia/finufft/actions/runs/14273170700
example pass:
https://github.com/DiamonDinoia/finufft/actions/runs/14273175303
=> added valgrind

python/cufinufft/pyproject.toml, python/finufft/pyproject.toml, tools/cufinufft/build-sdist.sh, tools/finufft/build-sdist.sh
Fixes some small issues to make the process a little more convenient.
=> Improve sdist-building process

.github/workflows/build_cufinufft_wheels.yml, .github/workflows/build_finufft_wheels.yml
Since windows-2019 is no longer supported.
=> Bring CI windows versions to 2022
