python/.gitignore, python/demo.py, python/finufft/__init__.py, python/finufft/build.py, python/finufft/interface.cpp, python/setup.py
Here's a proof of concept demo of how we might add Python bindings using [pybind11](https://github.com/pybind/pybind11). Most of the code is still boilerplate and the good stuff is all in `python/finufft/interface.cpp`. To test this, navigate to the `python` directory and run:
```bash
python setup.py build_ext --inplace
```
And if that succeeds, try:
```bash
python demo.py
```
To run an example that is equivalent to the one in `examples/example1d1.cpp`.
I've only implemented the `nufft1d1` function but I'd be happy to add the others if this looks good to you!
=> Proof of concept: adding Python bindings

python/demo.py, python/finufft/build.py, python/finufft/interface.cpp
I've added OpenMP support to the Python bindings. They seem to work on my Mac - the demo prints the following with `debug=1`:
```
1d1: ms=1000000 nf1=2000000 nj=1000000 ...
fftw plan                0.009 s
spread (ier=0):          0.329 s
fft (4 threads):         0.106 s
kernel fser (ns=10):     0.101 s
deconvolve & copy out:   0.012 s
freed
Finished nufft in 5.71e-01 seconds. Checking...
Error: 2.9159166847782386e-10
```
If you run something like:
```bash
cd python
rm -rf build
python setup.py build_ext --inplace
```
it should link to OpenMP if it's available. I haven't been able to test on Linux yet but on my Mac I had to do the following to get OpenMP set up:
```bash
brew reinstall gcc --without-multilib
brew reinstall fftw --with-openmp
CC=/usr/local/bin/gcc-6 CXX=/usr/local/bin/g++-6 …
```
=> Adding OpenMP support to Python bindings

src/cnufftspread.cpp, src/finufft1d.cpp, src/finufft2d.cpp, src/finufft3d.cpp, src/utils.cpp, src/utils.h
I started working on getting all this to build on Windows. I expect that this is something that you don't care about too much, but I've been trying to make my code as cross-platform as possible so I wanted to give it a shot! I'm not there yet, but I did switch out the timer code that you had for the C++ standard's `std::clock` instead of the deprecated `sys/time.h` code. This is probably a better interface either way.
I also cleared a few compiler warnings caused by ambiguous parens and formatting.
None of these changes should affect the output or compatibility (except to improve it!).
=> Modernizing timer code

src/cnufftspread.cpp, src/finufft1d.cpp, src/finufft2d.cpp, src/finufft3d.cpp, src/utils.cpp, src/utils.h
Reverts ahbarnett/finufft#9    since dfm's new std::clock seems not to give wall time, but sum of threads time.
=> Revert "Modernizing timer code"

docs/conf.py, docs/requirements.txt
See if this fixes the readthedocs issue.  This is a little sphinx hack just to make the import work. No formatting updates (yet).
=> Allow autodoc to work in minimal python environment

makefile
These only support double precision, so give the user an error if
they try to compile with single precision.
Fixes #21.
=> Check single precision when compiling MATLAB/Octave

src/spreadinterp.cpp, test/spreadbenchmark.py
It seems like the performance gap between type-1 and type-2 spreading was due to an explicitly set chunk size in the OpenMP dynamic scheduling. I found this by chance, when I noticed that threading had no positive effect on type-2 spreading for small problems.
Removing the explicit chunk size gives the following speedup on my machine:
```
gcc version 7.3.0
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
4 cores / 8 threads (hyperthreading)
=== Test: dim=3, M=100000, N=100000, tol=1e-15
Commit          | Spread spd      | Interp spd      | Spread err      | Interp err      
v1.0            | 1.4e+06 pts/s   | 2.39e+05 pts/s  | 7.57e-15        | 1.98e-14        
type2schedule   | 1.52e+06 pts/s  | 1.36e+06 pts/s  | 8.05e-15        | 1.98e-14        
| +8.6%           | +469.0%         | …
```
=> Improved type-2 parallellization

make.inc.mac
1. Added automatic mex binary determination.
2. Removed fortran from MFLAGS
3. Added comment to resolve the following warning:
ld: warning: object file (lib-static/libfinufft.a(finufft1d.o)) was built for newer OSX version
=> make.inc.mac improvements

requirements.txt
This lists the dependencies needed for installing building the
`finufftpy` packages. Fixes #59.
=> Add basic requirements.txt file

finufftpy/_interfaces.py, setup.py
Moved the module `finufft_cpp` (implemented as an extension, so visible as a .so/.pyd file) *inside* the top-level `finufftpy` module.
Having the `finufftpy_cpp` extension as a top-level module instead of a submodule of a "regular" python module is undesirable on two counts:
- It litters the users 'site-packages' folder with an isolated `finufftpy_cpp.so` (or `.pyd` in the case of Windows), with no obvious association with the `finufftpy` package. (Though it will get removed on `pip uninstall` automatically). So it's not considered best practice.
- It is not supported by tools such as `delocate` on mac os x (a tool that inspects the module for calls to shared libraries and packages them inside the `pip` package), and possibly other tools in the future that rely on modules following best …
=> Moved finufftpy_cpp as a submodule (interface unchanged).

finufftpy/_interfaces.py, setup.py
Reverts flatironinstitute/finufft#66.
Vineet, your PR broke the python tests:
import finufftpy.finufftpy_cpp as finufftpy_cpp
ModuleNotFoundError: No module named 'finufftpy.finufftpy_cpp'
=> Revert "Moved finufftpy_cpp as a submodule (interface unchanged)."

make.inc.power9
2 different compiler options: GNU or XL
COMP=ibm for xl, by default GNU compiler is used.
=> makefile for power9 cpu.

examples/simple1d1cf.c, include/dataTypes.h
Give dataTypes.h the same treatment as finufft.h, with #ifdef guards that check for the SINGLE flag. To fix the redefinition of typedefs (which is not allowed), these are replaced by macros. As a bonus, we can simplify the definitions of complex types using a COMPLEXIFY macro.
=> Guru interface v2 1h joakim

include/spreadinterp.h
This macro introduces cancellation errors when the frequencies are close
to –π or π. These errors then blow up after multiplying by N. By first
multiplying by N and then adding the correction term, we avoid this
problem at the cost of a slightly less transparent macro.
Fixes #103.
=> Fix RESCALE macro in spreadinterp

python/finufft/_interfaces.py
Make sure docstrings line wrap at 80 characters and add templated examples for the simple interfaces.
=> Fix line wrapping and add examples to Python docstrings

.gitattributes, examples/guru1d1c.c, examples/simple1d1c.c, examples/simple1d1cf.c, include/dataTypes.h, makefile, test/check_finufft.sh
This brings in Jonas's fixes to v2.0.0 for WSL:
- makefile switches (via MINGW) to windows versions of tasks: test, examples, clean, mex
- fixes to examples and test sources for complex math headers of windows
- check_finufft.sh bash script has 2nd arg switching to windows compat
This is most of it, I may have forgotten a couple.
=> windows compatibility for v2.0, focusing on WSL

docs/conf.py
The issue is perhaps that we need to mock `finufft._finufft` not `_finufft`. I also removed some of the other config options that we don't need.
This seems to work on my fork: https://finufft-janden.readthedocs.io/en/latest/python.html.
=> Try to make Python docs run again

python/requirements.txt, python/setup.py
Lots of old code there that is no longer needed. Also removed `requirements.txt` since the dependencies are already listed in `setup.py`. Finally add a check to make sure `libfinufft.so` is loadable from `ctypes` before proceeding with install.
=> Cleanup setup.py

makefile, python/README.md, python/setup.py
This reapplies some of the cleanup in #147, but doesn't break the explicit dynamic library linking that we're keeping. It solves the `finufftc` linking issue (#151), fixes the path detection when run as `setup.py install`, adds a Python `README` and includes this in the package description, and specifies minimum requirements for Python and NumPy. Also simplifies the `python` target in the `Makefile`.
=> Fix some issues with setup.py

makefile, python/setup.py
Since the Python library effectively hardcodes the path to the dynamic library, it makes more sense to keep it in the same directory instead of “installing” it into a system-specific directory. This is done by running `pip install -e` instead of just `pip install`. For this to work, we had to resolve an issue with the dummy C extension, which needs to be specified as a module name (that is, with dots) instead of a filename.
Closes #150.
=> Change python target to editable install

python/setup.py
Since it has no arguments, we need to specify `void` to avoid complaints
from `-Wstrict-prototypes`.
=> Fix prototype in dummy C extension

include/spread_opts.h, src/spreadinterp.cpp
The spreadSorted routine is largely thread safe, except in one section where the subgrid is
added back to the data_uniform array. Previously, a critical section was exclusively used to
block all entry into this routine from more than one thread at a time. While this routine is
relatively fast compared to other operations, this would lead to large queues when using large
numbers of threads.
As a simple "first-pass" way to address this issue, I tried using atomic operations on the
array entries in data_uniform that were being modified, rather than a blunt critical
section. Unfortunately, while atomic operations have better scaling behavior with large numbers
of threads, they are _very_ slow, and so hurt performance considerably with small thread
counts. This commit both adds an atomic …
=> Fixed #62 - Improve large thread count handling in spreadSorted

src/finufft.cpp, src/spreadinterp.cpp
This fixes #167.
This could only happen when epsmach*N > O(1), which is only poss in single-prec.
The cause was twofold: get_subgrid adding ns-1 before converting to BIGINT (hence its rounding differed from the index calc in spead_subproblem), and different rounding due to origin shift occurring with k{x,y,z}0 arrays.  This allowed spreading to overwrite the du array bounds.
Fix:
spreadSorted no longer shifts the subproblem k{x,y,z}0 arrays. Instead, the offsets from get_subgrid are now passed into spread_subproblem_{1,2,3}d.
This allows consistent rounding, according to int(ceil(kx - ns/2)), for all NU pts, where kx (or ky, kz) is always relative to the fine grid corner (after rescale and folding macro).
Assuming that max() and ceil() commute exactly in the floating-point implementation …
=> Singcrash: fix (single-prec) segfaults due to inconsistent rounding in spreading

docs/users.rst
The original link is becoming obsolete, the new one should be stable for several years at least.
=> Update reference to radio interferometry code

make.inc.manylinux, python/ci/build-wheels.sh
This fixes a couple of issues:
- It runs `make clean` to remove any remnants of already built libraries.
- It adds a `make.inc.manylinux` for greater compatibility with older chips (non-AVX).
- It updates and adds some comments.
Somehow I had written these a while ago and they never got into a PR.
=> Fix up build-wheels script

python/finufft/_interfaces.py
When running nufft type 3 transforms the following warning is displayed when running with numpy versions > 1.20.0: 
```/somedir/finufft/python/finufft/_interfaces.py:105: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations```
=> prevent deprecated warnings for nufft_type 3

makefile
We'd like to build and distribute a finufft.mex file that runs on multiple hosts with different processors. For this, we'd like to override `-march=native` when building finufft.
Append CFLAGS, FFLAGS, and CXXFLAGS set in environment so that we can set `CFLAGS="-march=x86-64"` when building the library.
=> makefile: Respect compiler flags from environment

python/finufft/_interfaces.py
Here is a patch to potentially close #202 .
I should remark that I feel the prior code was cleaner, though I suppose it wasn't guarding against contiguousness...
Anyway, this should push things along now.  @janden , could you confirm?
=> Fix some incorrect types in the 2.0.4 chk util method updates

src/finufft.cpp
Fixes bug where `free` was used to deallocate memory allocated with `new` (see allocation [here](https://github.com/wendazhou/finufft/blob/567e1f4f05cc8c03e750c19dc6265fad163359ec/src/finufft.cpp#L548))
=> Fix free / delete mismatch

CHANGELOG, contrib/legendre_rule_fast.cpp, contrib/legendre_rule_fast.h, include/spreadinterp.h, include/utils.h, include/utils_precindep.h, perftest/guru_timing_test.cpp, perftest/manysmallprobs.cpp, perftest/spreadtestnd.cpp, src/finufft.cpp, src/simpleinterfaces.cpp, src/spreadinterp.cpp, src/utils.cpp, src/utils_precindep.cpp, test/dumbinputs.cpp, test/finufft1d_test.cpp, test/finufft1dmany_test.cpp, test/finufft2d_test.cpp, test/finufft2dmany_test.cpp, test/finufft3d_test.cpp, test/finufft3dmany_test.cpp, test/testutils.cpp
only tested with executable
`perftest/spreadtestnd`
so far, works.
need to try out for all private functions in the library (non-user-facing), and the whole library including all examples in C++, C, Fortran.
The idea is to protect non-user-facing functions wtih a finufft:: namespace, yet leave the API unchanged (since it's designed to stay C-compatible).
This seems to be the only way to deal with static linking of finufft + cufinufft clash in
https://github.com/flatironinstitute/cufinufft/issues/138
So, I am not a C++ style expert. I want to keep it as simple as possible. I would love feedback if this is the way to continue.  (As that Issue discussion shows, using -fvisibility=hidden cannot help with static libs).
One question is: is having `using namespace finufft;` at top of all .cpp …
=> safe private library symbol namespace using finufft::

docs/python.rst, makefile, python/finufft/_interfaces.py
Fixes #216 and some other docs issues.
@lu1and10 Can you remind me why the dtype handling was in `setkwopts` in the first place? I had to move it out to make the default argument visible in the docs, but if I understand correctly, everything should still work.
=> Update py docs

CHANGELOG, docs/c.rst, docs/users.rst, include/finufft/defs.h, include/finufft/fftw_defs.h, include/finufft/finufft_eitherprec.h, include/finufft/test_defs.h, makefile
finufft_plan was already a pointer to the finufft_plan_s object, since we needed that for the high-level language interfaces (Joakim's idea).
However, finufft_plan_s was still defined in the public header.
Per Wenda's request, this PR makes finufft_plan_s private. Advantages:
* no user can become dependent on finufft_plan_s internals, which they should not
* fftw3.h is no longer in the public finufft.h
* finufft_plan_s can now use C++ mem mgmt and objects instead of restricted to C malloc/free. This will help Wenda.
Rather than create another header, I decided to add the plan definition to defs.h.
This also simplified the FFTW headers so that the only FFTW headers are in fftw_defs.h, no longer having a subset also in defs.h
Tests all work, but I'd appreciate confirmation.
=> Privplan: made finufft_plan_s object private

CMakeLists.txt, include/finufft/utils_precindep.h, src/utils_precindep.cpp
Hi all,
The time interface was using linux specific API that did not work on windows.
I replaced it using chrono since it is portable. Chrono accuracy is implementation dependent so if we want the highest accuracy we should query the performance counters on windows.
Now it is possible to build finufft with cmake on windows without minGW or similars.
Thanks,
Marco
=> Make the time interface windows compatible

include/cufinufft/spreadinterp.h, src/cuda/1d/spread1d_wrapper.cu, src/cuda/2d/spread2d_wrapper.cu, src/cuda/2d/spread2d_wrapper_paul.cu, src/cuda/3d/spread3d_wrapper.cu, test/cuda/cufinufft1d_test.cu, test/cuda/cufinufft2d_test.cu, test/cuda/cufinufft2dmany_test.cu, test/cuda/cufinufft3d_test.cu
There are a number of issues with the CUDA tests. Notably they don't properly detect `NaN` results. Some of the doc is wrong as well. This PR is a WIP to rectify that. See #271
=> Fix cuda tests that give NaN results and pass anyway

cufinufft/ci/docker/cuda11.0/Dockerfile-x86_64
So we're building from sm35 up to sm80 (widest span of CUDA 11).
=> cuda: update GPU architectures

src/spreadinterp.cpp
Sorry for the many pull requests ... I just keep finding interesting stuff :-)
This patch re-writes the inner loops of the 2D and 3D interpolation routines, with the goal of making them easier to vectorize by the compiler. On my laptop (AMD Ryzen 7 with AVX2) it almost doubles the interpolator performance on large 3D problems (216**3 grid, 100 million NU points).
=> make 2D/3D interpolation easier to vectorize

makefile, src/spreadinterp.cpp
Unless I'm missing something, it should be possible to perform the bin sorting without the additional `inv` vector. The resulting code is shorter and should also be faster, since it avoids the writing and subsequent reading of `inv`, and the times for random memory accesses may be partially overlapped with the bin index computations.
I didn't do any benchmarking however ...
=> avoid 'inv' array in bin_sort

CMakeLists.txt, cmake/setupCPM.cmake, docs/install_gpu.rst, test/CMakeLists.txt, tools/cufinufft/docker/cuda11.0/Dockerfile-x86_64
Currently, all builds have to include Finufft, which is a bit inconvenient when working with the cuFinufft code for two reasons:
– build takes longer
– other dependencies are required (FFTW)
This PR adds the option `FINUFFT_USE_CPU` which defaults to `ON` but can be set to `OFF` in order to build only cuFinufft.
=> Update cmake to allow GPU-only builds

python/cufinufft/setup.py, tools/cufinufft/build-wheels.sh, tools/cufinufft/distribution_helper.sh, tools/cufinufft/docker/cuda11.0/Dockerfile-x86_64
After merging the cufinufft code and reorganizing the directories, the standard wheel-building scripts (and setup.py) for cufinufft were broken. This PR fixes those scripts and cleans them up a little bit.
=> Fix cufinufft wheel building

python/cufinufft/cufinufft/_cufinufft.py
This is no longer used since options structure is no longer precision-dependent (`upsampfac` is always double).
=> Remove _get_ctypes in _cufinufft

CMakeLists.txt
PowerPC architecture does not have `-march=` flag (regardless of the OS). Use `-mtune=` instead.
=> Fix native optflag for PowerPC

python/finufft/setup.py
After the directory reorg, `setup.py` fails to find the README needed to fill in the package description. This corrects the path.
=> Fix finufft setup.py

python/cufinufft/cufinufft/_simple.py
This way, you can specify more advanced options, like `gpu_method` using the simple interface in the same way as the plan interface.
=> cuda: allow passing opts in cufinufft simple

docs/conf.py, python/cufinufft/cufinufft/__init__.py
Need to specify the proper paths for Python and make sure the modules are being exported properly for cufinufft.
Closes #328.
=> Update docs config for cufinufft

Jenkinsfile
Running on the K40's causes the tests to fail since `nvidia-smi` does not support querying the `compute_cap` flag for older drivers. While this can be bypassed by fixing the architecture, a second issue is that modern versions of `torch` won't run on that architecture, which we need for #326.
Simplest solution is therefore to require running Jenkins on the V100.
=> Constrain jenkins to use v100 GPUs

docs/c_gpu.rst, include/cufinufft.h, include/cufinufft/impl.h, perftest/cuda/cuperftest.cu, python/cufinufft/cufinufft/_cufinufft.py, python/cufinufft/cufinufft/_plan.py, src/cuda/cufinufft.cu, test/cuda/cufinufft1d_test.cu, test/cuda/cufinufft2d1nupts_test.cu, test/cuda/cufinufft2d_test.cu, test/cuda/cufinufft2dmany_test.cu, test/cuda/cufinufft3d_test.cu, test/cuda/interp1d_test.cu
This brings the interface in line with Finufft per #255. The `dim` and `type` (well, actually only `type`) were used to set `gpu_method`. Now this is set to `0`, an “auto” setting which results in `make_plan` choosing the most appropriate method for the type. (We'll be able to incorporate precision later as well, see #321.)
Resolves #255.
=> Remove `dim` and `type` from `cufinufft_default_opts`.

include/cufinufft/impl.h, python/cufinufft/tests/test_basic.py, python/cufinufft/tests/test_simple.py
Here method 2 fails since it requires too much shared memory. If the user doesn't specify a method (i.e., `gpu_method` is set to `0`, the “auto” value), we switch to method 1 in `makeplan` in this case to avoid crash during `execute`.
Closes #321.
=> Default to method 1 for 3D double-precision type 1 at low epsilon

python/finufft/finufft/_interfaces.py
To reduce ambiguity, we force dtypes to be complex for plan creation (this allows for the possibility of exposing a real dtype at some point if we want to).
Closes #311.
=> Deprecate real dtypes

docs/conf.py, docs/python_gpu.rst
Closes #364 
This now builds the docs even when cuda is unavailable (confirmed locally), and lists the new `nufft*d*` functions for cufinufft
=> Fix: allow cufinufft doc to build without shared lib available

docs/cex.rst, docs/devnotes.rst, docs/install.rst, docs/trouble.rst, examples/threadsafe1d1.cpp, examples/threadsafe2d2f.cpp, include/finufft/fftw_defs.h, makefile, src/finufft.cpp
This addresses almost all points made at #353 and should _actually_ fix the underlying issue of `fftw` thread safety.
* Remove `FFTW_PLAN_SAFE` and any mention, other than in changelog
* convert any `#pragma omp critical` around `FFTW` calls to using `std::lock_guard` -- fixes two issues
* Now works when `-DFINUFFT_USE_OPENMP=off`
* Should actually fix the bug. Critical only guaranteed that the section of interest was executed one thread at a time, but two different sections could still execute in tandem. I didn't see this cause a problem in multiple tests, but it would probably eventually happen.
=> bugfix/enhance: change all FFTW critical to mutex. nix FFTW_PLAN_SAFE

include/finufft/fftw_defs.h, src/finufft.cpp
This fixes the issue where only the first call to our makeplan routines would set the number of fftw threads. If a user wanted to change the number of fftw threads for different calls, it was impossible. 
Iniitially this commit also reverted the number of threads for future fftw_plan calls, but there is way to probe the current number of fftw threads when fftw < 3.3.9, and no trivial way to get a macro for the fftw version. This commit removes the "thread reversion" step of c923f89b (which was committed to master, failed CI because of an unsupported fftw version, and then reverted).
=> bugfix: set number of fftw threads for each makeplan call

python/cufinufft/setup.py
In short, after the python install, there are instances when `cufinufft` can't find `libcufinufft`. 
Right now, the `cufinufft` `setup.py` looks for `libcufinufft` and uses the `setuptools.Extension` to build a package initializer object that is _supposed_ to store the path to `libcufinufft` in it, except it doesn't. The fix is to add the relevant path to `runtime_library_dirs`. This automatically breaks windows builds, which we don't support anyway afaik.
=> bugfix: set rpath in cufinufft's setup.py

docs/install.rst, docs/python.rst, python/finufft/setup.py
This fixes a bunch of obsolete docs re how to build and test the Py wrapper.
We still have an issue that I cannot persuade `setup.py` to look in *both* `build/` and `lib/` for the `finufft_dlib` in the `ext_modules`.
Thus for the CMake user I include copying the .so over to `lib/` by hand = lame.
I hope this will get obsoleted by #374 anyway.
=> update py docs for testing and local build if CMake was used for compile

python/cufinufft/cufinufft/_plan.py
Small fixes to `cufinufft.Plan` docstrings. Mostly documenting some of the extra Plan options (`cufinufft_opts`).
Built docs and uploaded them to https://users.flatironinstitute.org/~janden/finufft-docs/python_gpu.html#cufinufft.Plan.
=> Update cufinufft py plan docstrings

python/cufinufft/cufinufft/_cufinufft.py, python/cufinufft/setup.py
Some smaller stuff like error messages and URLs but also fixing install bug under Rocky 8 and Ubuntu 20.04 (was already fixed for finufft). Finally, moves the `cufinufftc` C extension into the `cufinufft` package instead of leaving it in the site-packages root.
=> Update `setup.py` for cufinufft

.github/workflows/python_build_win.ps1, .github/workflows/python_wheel.yml, python/cufinufft/cufinufft/_cufinufft.py, python/finufft/finufft/_finufft.py, tools/cufinufft/build-wheels.sh, tools/finufft/build-wheels-linux.sh
Updates the code to use `importlib` instead of `imp` to make the library compatible with Python 3.12. Also updates the wheel building scripts to build wheels for Python 3.12 and test them.
=> Compile binary Python wheels for Python 3.12

include/cufinufft.h, src/cuda/cufinufft.cu
The prefix `h_` indicates that these are host pointers when in fact they are device pointers so switching to `d_` here. Also replacing `kx`, etc. with `x` for simplicity.
=> cuda: fix argument names in cufinufft C api

tools/cufinufft/build-library.sh
Goal here is to bring binary wheels down to less than 150 MB, which is the file size limit for PyPI. Here this is done by excluding compute capabilities 3.5 and 7.5, which brings us to 148 MB.
=> Remove compute capabilities 3.5 and 7.5 from cufinufft wheels

python/cufinufft/cufinufft/__init__.py, python/cufinufft/setup.py, python/finufft/finufft/__init__.py, python/finufft/setup.py
Should have all the details ironed out now for the full 2.2.0 release.
=> Bump Python versions to 2.2.0 proper

makefile
This addition fixes an issue where the examples could not be built on a Macbook Pro M3 running Mac OS Sonoma 14.2.1 with Clang. The failing CI on my fork does not seem to be related to this PR.
Cheers
Jonas
=> Fix examples on Mac OSX with Apple Silicon

docs/opts.rst
The [Options parameter](https://finufft.readthedocs.io/en/latest/opts.html) page has a "Summary and quick advice" section which details all options.
The flag descriptions further down the page don't always match the summary however.
This PR corrects the docs accordingly.
=> Optional parameters: make descriptions match table summary.

src/finufft.cpp
Enforce nthreads = 1 for single threaded lib, to improve the case that single threaded finufft lib running with nthreads != 1 gives inf/nan error flatironinstitute/jax-finufft#73 and flatironinstitute/finufft#430.
=> Enforce nthreads = 1 for single threaded lib

CHANGELOG, docs/opts.rst, src/finufft.cpp, src/spreadinterp.cpp
material changes are
* remove capping at omp_get_max_nthreads(), based on Marco & team discussion 5/7/24
* warning user if they do the above; and if they try nthr>1 in OMP=OFF build
* bin-sort max thread number now properly overridden by spopts.nthreads, and (with higher priority) by spopts.sort_threads (which also overrides the drop-to-single-thread heuristic)
* no thread caps in spreadinterp; except if OMP=OFF now enforce nthr=1.
Here's detailed logic notes (also in gdoc):
OMP=OFF: (single-threaded). Always enforce nthr=1; warning raised (makeplan stage only) if user sets opts.nthreads>1.
OMP on: user can set any nonzero nthr; warning given if showwarn=1 & exceeds omp_max_threads().
At the makeplan stage, opts.nthreads is rewritten with actual # threads used (by fft, etc), thus it is …
=> revisit logic for choosing number of threads in various FINUFFT tasks

docs/users.rst
I've released the first version of [nifty-ls](https://github.com/flatironinstitute/nifty-ls/), which uses finufft or cufinufft to accelerate Lomb-Scargle for astronomers. It's many times faster than the usual Astropy method, and orders of magnitude more accurate! Thanks @ahbarnett and @dfm for your help.
One challenge in using finufft was setting an appropriate default number of threads (for 1D type-1, both batched and unbatched). I implemented some heuristics based on the problem size, but it's probably not optimal/portable. I realize it's a hard problem to solve, but it would be great if finufft could implement some of this upstream!
=> users.rst: add nifty-ls

CHANGELOG, Jenkinsfile, include/cufinufft.h, python/cufinufft/cufinufft/_cufinufft.py, src/cuda/cufinufft.cu
For compatibility with FINUFFT.
This is quite an invasive patch and I'm not sure it's doing the right thing in several places (in particular, I'm not certain that CUDA is happy taking `int64_t` for block dimensions, etc.). That being said, it is compiling and tests are passing, so that's something.
=> cuda: update interface to take 64-bit M

include/cufinufft/contrib/helper_cuda.h, include/cufinufft/impl.h, include/cufinufft/types.h, src/cuda/1d/spread1d_wrapper.cu, src/cuda/2d/spread2d_wrapper.cu, src/cuda/3d/spread3d_wrapper.cu, src/cuda/memtransfer_wrapper.cu
This PR attempts to resolve the issue that `cudaMallocAsync/cudaMallocFree` is not supported based purely on compute capability, but is device dependent as well. To resolve this I probe for async memory pool capabilities as suggested at https://github.com/kokkos/kokkos/issues/7044 and then store that info on the plan struct. `free` and `malloc` calls are then all wrapped, passing this result so that the appropriate call is made.
We should probably print a warning, but unlike the cpu version, there is no verbosity option supplied to the library, so I wasn't sure the best way to provide a message without spamming the user if they don't care. A short-term solution would be to just make it print the result only on the first failure, and then mark the failure visited via a `static bool`.
=> cuda: use sync malloc/free when async not supported #445

src/spreadinterp.cpp
Reverts flatironinstitute/finufft#477
There are some intermediate commits(related to performance comparison and may check back later, @mreineck 's unaligned store ker-sym version,  static const, and conditional declaration, etc...) need to be kept, so reverting and make a new PR to keep the commits history.
=> Revert "Horner's rule for polynomial evaluation with symmetry idea diccussed in discussions #461"

test/basicpassfail.cpp, test/finufft1d_test.cpp, test/finufft2d_test.cpp, test/finufft3d_test.cpp
This should fix indeterminacy with DUCC / fastmath/ OSX, etc, and in general less random failures.
There is no way to apply this to the "many" tests, since they don't have the l2 err metric (we could create a different threshold for them?) They also can't be applied to basicpassfail, unless we implement the direct transform there too, but that has a fixed seed and deterministic rand generation, so should be less susceptible.
=> l2 err overrides one-output err in errmax for math test exit codes

CMakeLists.txt
In the current state, it is not possible to install the finufft library using CMake: Running `cmake --install build` as described in the documentation, does not have any effect. This commit fixes this issue.
=> Fix installation using CMake

fortran/CMakeLists.txt
Currently, we get the following error when trying to build with `FINUFFT_BUILD_FORTRAN=ON`:
```
[ 48%] Building Fortran object fortran/CMakeFiles/fort_guru1d1.dir/examples/guru1d1.f.o
cd /home/janden/projects/finufft/build/fortran && /usr/bin/gfortran  -I/home/janden/projects/finufft/include -O3 -c /home/janden/projects/finufft/fortran/examples/guru1d1.f -o CMakeFiles/fort_guru1d1.dir/examples/guru1d1.f.o
/home/janden/projects/finufft/fortran/examples/guru1d1.f:19: Error: Can't open included file 'fftw3.f'
```
This PR fixes this by explicitly including `FINUFFT_FFTLIBS` as a linked library for the examples.
Note: There is a lot of noise here due to the cmake-format hook which forces reformatting. Perhaps it would be good to do this across all CMakeLists.txt in a single commit?
=> Include fftw3 as a dep for fortran examples

python/cufinufft/pyproject.toml
Instead of hardcoding it in pyproject.toml, have it read (using regex) from cufinufft/__init__.py. This way we have a single source of truth for the cuFinufft Python version.
=> Make cufinufft version dynamic

python/cufinufft/pyproject.toml, python/finufft/pyproject.toml
This will give a slight performance hit, but ensure that our wheels are able to run on older CPUs. If a user needs the increased performance that comes with `-march=native`, we ask them to compile the package from source.
=> Do not compile Python wheels with -march=native

Jenkinsfile, python/cufinufft/cufinufft/_cufinufft.py, python/cufinufft/tests/test_fallback.py, python/finufft/pyproject.toml, python/finufft/test/test_fallback.py
If `libcufinufft` is not found in the package directory, the code is supposed to fallback to a system `libcufinufft`, but this is currently broken (missing import). This PR fixes the issue and also adds tests (in cufinufft and finufft) to make sure that the fallback mechanism works properly.
=> Fix cufinufft fallback

CMakeLists.txt
This should only be compiled if `FINUFFT_BUILD_FORTRAN` is set to `ON`.
=> Exclude fortran/finufftfort.cpp by default

.github/workflows/python_build_wheels.yml, python/cufinufft/examples/example2d2_pycuda.py
By forcing install of gcc and fftw compatible with macOS 12 (Monterey), we can ensure the binaries are compatible with that and later versions of macOS. As macOS 12 came out in October 2021, that gives us a three-year window for both x86_64 and arm64 binary wheels on macOS.
=> Make Python binary wheels compatible with macOS 12

python/finufft/pyproject.toml
This will only be triggered during `cibuildwheel`, not for regular source installs.
Closes #540.
=> Prevent -march=native for binary Python wheels

python/cufinufft/cufinufft/_cufinufft.py, python/finufft/finufft/_finufft.py
For older (<1.25) versions of NumPy, calling `np.ctypeslib.load_library` results in the logging level being reset. This workaround checks for that bug and preserves the logging level.
Incorporates fix suggested by @lu1and10 in https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/1168#issuecomment-2322349795
=> Fix logging bug caused by np.distutils

.github/workflows/python_build_wheels.yml, python/finufft/pyproject.toml
This PR does a few things:
* Make cmake output a verbose makefile that tells us what commands are actually run.
* Move some of the CIBW config settings for Windows into pyproject.toml.
* Force wheels to be built with `-march=x86_64` to enhance compatibility (this seems to be an issue in particular running wheels on macOS with x86_64 compatibility mode on ARM chips). This excludes the macOS arm64 wheels, of course.
=> Solve issues with Python wheel building

tools/cufinufft/distribution_helper.sh, tools/cufinufft/docker/README, tools/cufinufft/docker/cuda11.2/Dockerfile-x86_64, tools/cufinufft/docker/cuda11.2/README, tools/cufinufft/docker/cuda11.8/Dockerfile-x86_64, tools/cufinufft/docker/cuda11.8/cuda.repo, tools/cufinufft/docker/cuda12.0/Dockerfile-x86_64
This brings the cufinufft wheel building up to date with the new skbuild-based approach. To build the wheels, make sure docker is installed and run `tools/cufinufft/distribution_helper.sh`. The wheels should then end up in `dist`.
=> Update cufinufft wheel building scripts

tools/cufinufft/docker/cuda11.2/Dockerfile-x86_64, tools/cufinufft/docker/cuda11.8/Dockerfile-x86_64, tools/cufinufft/docker/cuda12.0/Dockerfile-x86_64, tools/finufft/docker/Dockerfile-x86_64
in jenkins, `image:latest` won't know to automatically update itself, so can run an old cached version. This is likely causing issues with invalid `python3` commands.
https://github.com/flatironinstitute/finufft/pull/549#issuecomment-2338504811
=> ci: tag all manylinux docker images

python/finufft/finufft/_interfaces.py
Fixes #556.
This is a bugfix PR and should also be applied to 2.3.X.
=> Fix dtype check in simple Python interface

.github/workflows/cmake_ci.yml
=> Add cibuildwheel to large CI matrix

include/cufinufft/impl.h, test/cuda/CMakeLists.txt
Currently, type 3 crashes when invoked with default GPU method (`opts.gpu_method = 0`). This detects the default setting and sets it to 1.
=> Automatically set method for GPU type 3

src/cuda/cufinufft.cu
Since we don't use this, no need to check if it's valid. This lets us call `makeplan` with `nmodes` set to `NULL`.
=> Ignore nmodes input for type 3 on GPU

makefile, python/finufft/pyproject.toml
on my linux system, this fixes #585
Should be platform-indep - could someone else check it works?
=> makefile: pass DUCC option to Python sk-build via CMAKE_ARGS in pip

include/finufft/finufft_core.h, perftest/guru_timing_test.cpp, src/fft.cpp, src/finufft_core.cpp
This demonstrates how variables depending on problem dimensionality could be merged into `std::array`s, and how it potentially simplifies the code.
This is not yet complete:
- I'm not happy with the variable names yet. For example, I renamed `nf1, nf2, nf3` to `nf123`, since the obvious candidate `nf` was already used for storing the product `nf1*nf2*nf3`, and I didn't want to do big refactorings for this demonstrations.
- there are more good candidates in the interface of  `spreadinterp`, which I haven't looked at much, mostly because there is a clash between `finufft_core.h`, where integer quantities are usually `BIGINT`,and `spreadinterp.h`, where they tend to be `UBIGINT`. While it is possible to convert individual integers on the fly when crossing the interface, the same does not …
=> potential way of implementing discussion #587

python/cufinufft/cufinufft/_cufinufft.py, python/cufinufft/cufinufft/_plan.py, python/cufinufft/tests/test_basic.py, python/cufinufft/tests/utils.py, src/cuda/3d/cufinufft3d.cu
Adds a type 3 interface in Python for the GPU code.
=> GPU type 3 in Python interface

python/cufinufft/cufinufft/_plan.py, python/cufinufft/tests/test_basic.py, python/finufft/finufft/_interfaces.py, python/finufft/test/test_finufft_plan.py
Makes all the attributes private by underscoring their names. They can still be accessed in the public interface, but only as (read-only) properties. This applies for both CPU and GPU code.
Fixes #565.
=> Make Python plan attributes private

src/finufft_core.cpp
This removes the temporary `phihatk` arrays in the `setpts` method for type 3 transforms. It also reduces the amount of large array accesses happening in this function.
=> Tweak type 3 setpts

src/cuda/CMakeLists.txt
libcufinufft.so is now in the root of the build folder.
=> Fixes https://github.com/flatironinstitute/finufft/issues/607

docs/python.rst, docs/python_gpu.rst
=> Add source install instructions for gpu

include/finufft/heuristics.hpp
Addresses https://github.com/flatironinstitute/finufft/pull/651#issuecomment-2845012866
=> using 2.00 when withing two digits of machine precision

CMakeLists.txt
This is needed to avoid shipping extraneous code related to the Fortran interface in the Python sdist. We should only add Fortran-specific source files when the FINUFFT_BUILD_FORTRAN flag is passed to cmake.
=> Don't include Fortran sources by default

matlab/finufft_isgpuarray.m
The MATLAB interface checks if inputs are `gpuArray` on every call to `setpts` and `execute`, via the routine `finufft_isgpuarray`. This routine operates by calling `exist('isgpuarray')`, which is slow. When performing many small NUFFTs, `finufft_isgpuarray` can actually be the bottleneck. This PR speeds up `finufft_isgpuarray` so the overhead is negligible.
Example:
```
N = 64;
M = 1e3;
plan = finufft_plan(2, [N N], 1, 1, 1e-9);
tic
for k = 1:10000
x = 2*pi*rand(M,1);
y = 2*pi*rand(M,1);
c = randn(N)+1i*randn(N);
plan.setpts(x,y);
f = plan.execute(c);
end
toc
```
Before this PR:
```
Elapsed time is 28.521582 seconds.
```
After this PR:
```
Elapsed time is 5.723936 seconds.
```
=> Speed up gpuArray check in MATLAB interface

include/finufft/finufft_utils.hpp, src/finufft_core.cpp
This PR introduces an inline helper function getCachedOptimalThreadCount() that caches the result of getOptimalThreadCount() using a static local variable.
As discussed in #693 by @lgarrison , @DiamonDinoia and @lu1and10 , the previous implementation invoked getOptimalThreadCount() at each plan call, triggering redundant system calls. Caching its result avoids this overhead by ensuring the thread count is computed only once.
=> Get optimal thread count skip
